language: php
php:
  - 5.6
  - 7.0
install: composer install --no-interaction --prefer-source
script:
  - php vendor/bin/phpcs --config-set installed_paths ../../../
  - vendor/bin/phpunit vendor/squizlabs/php_codesniffer/tests/AllTests.php
